### ISSUE TITLE
+dnssec for -i

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dnsext#101]
What is the expected behavior for `dug -i +dnssec`?
It seems to me that `+dnssec` does not change anything for `-i` currently.

**Comment by khibino** [comment]
Only the result record returned will change.
For example, a record of type `RRSIG` is returned only when `+dnssec` is added.

**Comment by kazu-yamamoto** [comment]
We should discuss semantics for each plus option.

**Comment by kazu-yamamoto** [comment]
Closing.
