### ISSUE TITLE
no delegation:

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dnsext#121]
`dug -demo -i` displays "no delegation:" with black color.
It would be nice if it is colored with yellow.

**Comment by kazu-yamamoto** [comment]
@khibino Ping.

**Comment by khibino** [comment]
If I do that, I will get yellow in the middle of the chain of successful (green) DNSSEC validation of DS, what do you think?

**Comment by khibino** [comment]
In order to get a successful (green) final validation result,
A green chain from the beginning to the end is required to obtain a successful (green) final result.

If the green chain is interrupted in the middle, no green will appear after that.

```
. ----> z. ----> a.b.z. ----> p.a.b.z. (Green result)
    G        G            G


. ----> z. ----> c.z. ----> q.c.z. (Yellow result)
    G        Y          Y


. ----> z. ----> d.z. ----> r.d.z. (ServFail result)
    G        Y          R


G: delegation with verified DS (Green)
Y: delegation with no verification (Yellow)
R: delegation with DS verification failure / delegation without SEP DNSKEY (Red)
```

**Comment by kazu-yamamoto** [comment]
I'm talking about the following example.

```
% dug -i --demo www.mew.org
...
fill delegation - no DS, so no verify: "org." -> "mew.org." (YELLOW)
zone: "mew.org.":
	"ns1.mew.org." ["202.238.220.92"]
	"ns2.mew.org." ["210.155.141.200"]
iterative: query ("www.mew.org.",A) servers: 202.238.220.92 210.155.141.200
    query "www.mew.org." A to 202.238.220.92#53/UDP
    query "www.mew.org." A to 210.155.141.200#53/UDP
    query "www.mew.org." A to 202.238.220.92#53/UDP: win
no delegation: "mew.org." -> "www.mew.org." (HERE HERE HERE)
resolve-exact: query ("www.mew.org.",A) servers: 202.238.220.92 210.155.141.200
    query "www.mew.org." A to 202.238.220.92#53/UDP
    query "www.mew.org." A to 210.155.141.200#53/UDP
    query "www.mew.org." A to 202.238.220.92#53/UDP: win
no verification - no DS, "www.mew.org." A (YELLOW)
;; 195usec
```

If this black color is intentional, let's close this.

**Comment by khibino** [comment]
Yes. This is intentional.

----

"www.mew.org." is not a zone apex, but a domain name in the "mew.org." zone.
Therefore there is no delegation "mew.org." -> "www.mew.org.".


Let's look at a slightly different example.

```
% dug -i --demo iij.ad.jp
...
delegation - verification success - RRSIG of DS: "." -> "jp." (GREEN)
...
no delegation: "jp." -> "ad.jp."  (HERE, NO DELEGATION)
...
delegation - verification success - RRSIG of DS: "jp." -> "iij.ad.jp." (GREEN)
...
verification success - RRSIG of "iij.ad.jp." A (GREEN)
;; 52usec
```

In this example, "ad.jp." is not a zone apex, but a domain name in the "jp." zone.
Therefore, the delegation "jp." -> "ad.jp." does not exist.
(The delegation is "jp." -> "iij.ad.jp.")

In this example, if "no delegation" is output in yellow, yellow will be output in the middle of the green chain.
