### ISSUE TITLE
Not uniform result of Do53 resolve

### ISSUE THREAD

**Issue by khibino** [kazu-yamamoto/dnsext#169]
The result type of Do53's resolve is `IO (Either DNSError Result)`.

https://github.com/kazu-yamamoto/dnsext/blob/fc3b35bc3cae942cc562a2a281f30d4c66b3f85a/dnsext-do53/DNS/Do53/Resolve.hs#L40
https://github.com/kazu-yamamoto/dnsext/blob/fc3b35bc3cae942cc562a2a281f30d4c66b3f85a/dnsext-do53/DNS/Do53/Types.hs#L241

The way to end with `DNSError` is not uniform. There are two ways as follows.
* Buried in `IO` using `throwIO`
* Returned by `(pure . Left)`

In the current implementation, are the two semantically distinct?

**Comment by kazu-yamamoto** [comment]
Please try the `io-error` branch and tell me what happens.

**Comment by khibino** [comment]
Even in this branch, do53 seems to raise DecodeError / NetworkFailure / RetryLimitExceeded / TimeoutExpired exceptions via IO.
