### ISSUE TITLE
"typeNN" for the Read instance of TYPE

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dnsext#20]
To specify a unknown type to `dug`, it would be nice if the `Read` instance of `TYPE` could interpret "typeNN":

```
% dug www.example.com type65
```

@khibino What do you think?

**Comment by khibino** [comment]
I think it's good too.

**Comment by kazu-yamamoto** [comment]
Sorry but I made a mistake. I pushed related commits to `main` instead of sending a PR.
