### ISSUE TITLE
Using the network-udp package

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dnsext#28]
- [x] Removing `#ifdef`
- [x] Passing `IO Time`
- [x] Using the network-udp package

**Comment by khibino** [comment]
draft-ietf-dnsop-avoid-fragmentation: Fragmentation Avoidance in DNS

https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-avoid-fragmentation-08

**Comment by kazu-yamamoto** [comment]
@khibino FYI: https://github.com/kazu-yamamoto/network-udp

**Comment by kazu-yamamoto** [comment]
Done.
