### ISSUE TITLE
New API for auto-update

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/dnsext#61]
@khibino Check them out!

- https://github.com/kazu-yamamoto/wai/commit/cd647d5721bdf6bad5bdf68f973ee6702bd03fd5
- https://github.com/kazu-yamamoto/dnsext/commit/82191d6eda86fd1a6231a4c90cfac26ac13bdd83

If you test this, I will update `auto-update`!

**Comment by kazu-yamamoto** [comment]
Use the following instead:

- https://github.com/kazu-yamamoto/wai/commit/83ebaeb13d0f2b5b2229aca4168f2c5c27f33df1
- https://github.com/kazu-yamamoto/dnsext/commit/7195f3dabe5711e4a37f17defa419d03eb7d6767

**Comment by khibino** [comment]
@kazu-yamamoto

I made a OneShot module by extracting the essence of reaper thread management.

https://github.com/khibino/wai/commit/e9f5ab933b9ad69d7df643fab53be41296dbcd82

In the case of DNS Cache, to register only the expire process in OneShot as follows,
I think it is simple to implement without depending on the data structure of the Cache.
What do you think?

https://github.com/khibino/dnsext/commit/70901d7a12f59f51b4ca85c7b1d54de49dfcaaf4

**Comment by kazu-yamamoto** [comment]
The `OneShot` implementation is NOT power safe.

`Reaper` does not consume if the target is null.
Adding an entry wake the reaper up when it is sleeping.

**Comment by khibino** [comment]
The user of `OneShot` can handle not to `register` when the value is `null`. In that case, it is considered to be power safe.

**Comment by khibino** [comment]
Add handy repeatable, and small example to OneShot

https://github.com/khibino/wai/commit/0a3f794984318c63bd40f62c3d09d0b337d71bca

updated DNS cache

https://github.com/khibino/dnsext/commit/ec80bb4553d156d6e318aac6968567b2fdad7dae

**Comment by khibino** [comment]
Added #68 about `lookup` wait

**Comment by kazu-yamamoto** [comment]
Let's close this.
