### ISSUE TITLE
Reaper: lazy-thunk makes `lookup`s wait

### ISSUE THREAD

**Issue by khibino** [kazu-yamamoto/dnsext#68]
Reaper takes advantage of `atomicIORef'` and makes good use of pointers and lazy-thunk to achieve serial semantics `insert`, `prune`, and `lookup` for PSQ.

However, if scaling `lookup` is more important than immediacy of update, the previous method has disadvantages.

Consider the case where there are many threads issuing `lookup`s immediately after an update that takes time to resolve the lazy-thunk (e.g., a `prune` that discards many values).
Then all `lookup` threads will wait until the lazy-thunk is resolved.

**Comment by kazu-yamamoto** [comment]
I think this can impliment with two `IORef`s, one for update, the other is for lookup, the value of the first one overrides the second one after the update is finished.
