### ISSUE TITLE
Unfriendly display of `DNSTime`

### ISSUE THREAD

**Issue by khibino** [kazu-yamamoto/dnsext#91]
In the following example, the values of the time `rrsig_expiration` and `rrsig_inception`, which indicate the validity period of the signature, are difficult to understand

```
 $ dug iij.ad.jp. A +dnssec
;; 202.238.220.76#53/UDP, Tx:38bytes, Rx:223bytes, 31usec

;; HEADER SECTION:
;Standard query, NoError, id: 23611
;Flags: Recursion Desired, Recursion Available


;; OPTIONAL PSEUDO SECTION:
;UDP: 4096, Data:[]

;; QUESTION SECTION:
;iij.ad.jp.		IN	A

;; ANSWER SECTION:
iij.ad.jp.	300(5 mins)	IN	A	202.232.2.191
iij.ad.jp.	300(5 mins)	IN	RRSIG	RD_RRSIG {rrsig_type = A, rrsig_pubalg = RSASHA256, rrsig_num_labels = 3, rrsig_ttl = 300(5 mins), rrsig_expiration = 1687446606, rrsig_inception = 1684854606, rrsig_key_tag = 10788, rrsig_zone = "iij.ad.jp.", rrsig_signature = \# 128 8a13aa498e3291463ef0f9573f47330232123d2bb53a4713d820948fa562d251784c86abb4b448d2676f412500dad27cc331c7d222d61be307849f2d0cff5da4379014a36af7912075647951d8b36efdab309bfb6af54f9ffcefa77e0123b18e23cf0cf117d17e610e4c9aaab990daf86e23e9b4bf4bf90413455b4b1c9873d7}

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:
```

**Comment by kazu-yamamoto** [comment]
Where can I find the spec of DNS time?

**Comment by khibino** [comment]
"Signature Expiration and Inception Fields" https://datatracker.ietf.org/doc/html/rfc4034#section-3.1.5
and referenced from there
"Serial number arithmetic" https://datatracker.ietf.org/doc/html/rfc1982
was found.

**Comment by kazu-yamamoto** [comment]
RFC 4034 says:

> An RRSIG RR can have an Expiration field value that is
> numerically smaller than the Inception field value if the
> expiration field value is near the 32-bit wrap-around point or
> if the signature is long lived.

I don't understand this.
